#!/usr/bin/env bash 
# Installs and setup haproxy 

apt-get -y update 
apt-get install -y haproxy


sudo sh -c 'echo " 
frontend http 
    bind *:80 
    mode http 
    default_backend web-backend 

backend web-backend 
    balance roundrobin 
    server 257575-web-01 18.209.223.170:80 check 
    server 257575-web-02 18.210.17.132:80 check 
" >> /etc/haproxy/haproxy.cfg'

sudo service haproxy restart
